import { JobApplication } from "./types";

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: "app-1",
    company: "Stripe",
    role: "Senior Full Stack Engineer",
    status: "Interviewing",
    priority: "High",
    location: "Remote (US/Europe)",
    salary: "$165,000 - $195,000",
    date_applied: "2026-08-10",
    deadline: "2026-08-30",
    job_url: "https://stripe.com/jobs",
    resume_version: "FullStack_AI_Resume_v3.pdf",
    notes: "Spoke with hiring manager Alex. Emphasized high-throughput payments architecture and Next.js frontend optimizations.",
    job_description: "We are looking for a Senior Full Stack Engineer to lead infrastructure and developer platform interfaces across Stripe's core billing teams.",
    match_insights: {
      score: 94,
      strengths: ["React / Next.js", "TypeScript", "Distributed Systems", "API Design", "PostgreSQL"],
      gaps: ["Ruby on Rails internals"],
      summary: "Exceptional profile match with strong frontend architecture and high-scale backend experience.",
    },
    contact: {
      name: "Alex Vance",
      role: "Engineering Manager",
      email: "avance@stripe.com",
      linkedin: "https://linkedin.com/in/alexvance",
    },
    tasks: [
      {
        id: "task-1",
        title: "Complete System Design prep (Payments Ledgers)",
        due_date: "2026-08-26",
        completed: false,
      },
      {
        id: "task-2",
        title: "Send follow-up thank you note to recruiter",
        due_date: "2026-08-23",
        completed: true,
      },
    ],
    interview_rounds: [
      {
        id: "round-1",
        round_name: "Recruiter Screen",
        date: "2026-08-14",
        interviewer: "Sarah Jenkins",
        notes: "Passed recruiter phone screen smoothly. Discussed salary expectations and remote workflow.",
        status: "Passed",
      },
      {
        id: "round-2",
        round_name: "Technical Architecture & System Design",
        date: "2026-08-27",
        interviewer: "Alex Vance & Staff Engineer",
        notes: "Scheduled for 60 minutes covering distributed state machine and caching.",
        status: "Scheduled",
      },
    ],
    created_at: "2026-08-10T10:00:00Z",
    updated_at: "2026-08-24T18:00:00Z",
  },
  {
    id: "app-2",
    company: "Anthropic",
    role: "AI Application Engineer",
    status: "Interviewing",
    priority: "High",
    location: "San Francisco, CA (Hybrid)",
    salary: "$180,000 - $220,000 + Equity",
    date_applied: "2026-08-12",
    deadline: "2026-09-01",
    job_url: "https://anthropic.com/careers",
    resume_version: "AI_Systems_Resume_v4.pdf",
    notes: "Focusing on agentic workflows, prompt chaining, streaming SSE response UI, and evaluation benchmarks.",
    job_description: "Build delightful, robust developer interfaces and multimodal tool-use interfaces for Claude and next-gen agent models.",
    match_insights: {
      score: 91,
      strengths: ["LLM Tool Calling", "FastAPI / Python", "Vector DBs (Qdrant)", "TailwindCSS", "Agentic RAG"],
      gaps: ["Evaluation framework depth (RAGAS)"],
      summary: "High synergy with modern GenAI stack, vector retrieval, and responsive UI tooling.",
    },
    contact: {
      name: "Marcus Chen",
      role: "AI Technical Recruiter",
      email: "marcus.chen@anthropic.com",
      linkedin: "https://linkedin.com/in/marcuschen-ai",
    },
    tasks: [
      {
        id: "task-3",
        title: "Review Agent loop failure mode case studies",
        due_date: "2026-08-28",
        completed: false,
      },
    ],
    interview_rounds: [
      {
        id: "round-3",
        round_name: "Technical Take-Home & Screen",
        date: "2026-08-18",
        interviewer: "Marcus Chen & Core Team",
        notes: "Take-home submitted: Multi-turn agent evaluator.",
        status: "Passed",
      },
      {
        id: "round-4",
        round_name: "Live AI Coding & Evaluation Round",
        date: "2026-08-29",
        interviewer: "Lead AI Research Engineer",
        notes: "Live debugging of tool-use execution graph.",
        status: "Scheduled",
      },
    ],
    created_at: "2026-08-12T11:30:00Z",
    updated_at: "2026-08-24T19:15:00Z",
  },
  {
    id: "app-3",
    company: "Vercel",
    role: "Frontend Platform Engineer",
    status: "Offer",
    priority: "High",
    location: "Remote (Global)",
    salary: "$160,000 - $185,000 + Stock",
    date_applied: "2026-07-28",
    job_url: "https://vercel.com/careers",
    resume_version: "Frontend_Platform_Resume.pdf",
    notes: "Offer letter received! Reviewing benefits, compensation breakdown, and start date options.",
    job_description: "Help build the next generation of web infrastructure tools, edge rendering engines, and dashboard UI.",
    match_insights: {
      score: 96,
      strengths: ["Next.js 14 App Router", "Server Components (RSC)", "TailwindCSS", "Edge Computing", "Web Vitals"],
      gaps: ["Turbopack internals"],
      summary: "Almost perfect alignment with Vercel's core frontend and platform toolchain.",
    },
    contact: {
      name: "Elena Rostova",
      role: "Senior Talent Partner",
      email: "elena.r@vercel.com",
    },
    tasks: [
      {
        id: "task-4",
        title: "Prepare counter-offer & equity vesting questions",
        due_date: "2026-08-27",
        completed: false,
      },
      {
        id: "task-5",
        title: "Review health insurance & 401(k) match documentation",
        due_date: "2026-08-28",
        completed: false,
      },
    ],
    interview_rounds: [
      {
        id: "round-5",
        round_name: "Final Leadership & Offer Discussion",
        date: "2026-08-22",
        interviewer: "VP of Engineering",
        notes: "Extended official offer. Received formal package via email.",
        status: "Completed",
      },
    ],
    created_at: "2026-07-28T09:00:00Z",
    updated_at: "2026-08-23T14:20:00Z",
  },
  {
    id: "app-4",
    company: "Datadog",
    role: "Senior Software Engineer - Observability",
    status: "Applied",
    priority: "Medium",
    location: "New York, NY (Hybrid)",
    salary: "$150,000 - $175,000",
    date_applied: "2026-08-20",
    deadline: "2026-09-10",
    job_url: "https://datadoghq.com/careers",
    resume_version: "FullStack_AI_Resume_v3.pdf",
    notes: "Applied directly through employee referral link. Awaiting recruiter initial response.",
    job_description: "Build real-time metrics dashboards, telemetry pipelines, and distributed tracing UI.",
    match_insights: {
      score: 86,
      strengths: ["TypeScript", "Golang / Python", "Telemetry & Logging", "Postgres", "Docker"],
      gaps: ["OpenTelemetry collector custom plugins", "Kafka cluster tuning"],
      summary: "Strong candidate match for frontend observability and backend metrics pipeline.",
    },
    contact: {
      name: "Referral: David Miller",
      role: "Staff Engineer at Datadog",
      email: "dmiller.referrals@datadog.com",
    },
    tasks: [
      {
        id: "task-6",
        title: "Follow up with David if no update by Friday",
        due_date: "2026-08-29",
        completed: false,
      },
    ],
    interview_rounds: [],
    created_at: "2026-08-20T15:00:00Z",
    updated_at: "2026-08-20T15:00:00Z",
  },
  {
    id: "app-5",
    company: "Linear",
    role: "Product Engineer",
    status: "Bookmarked",
    priority: "High",
    location: "Remote (US / EU)",
    salary: "$155,000 - $185,000",
    date_applied: "2026-08-24",
    job_url: "https://linear.app/careers",
    resume_version: "FullStack_AI_Resume_v3.pdf",
    notes: "Preparing tailored cover letter highlighting keyboard-first UI experience and offline sync replication.",
    job_description: "We are crafting the next generation of software project management tools. High aesthetic standards and obsessive performance focus required.",
    match_insights: {
      score: 89,
      strengths: ["Keyboard Shortcuts UX", "Optimistic UI Updates", "TailwindCSS / CSS", "State Machines (XState)", "React"],
      gaps: ["Local-first sync engine (ElectricSQL/CRDTs)"],
      summary: "High visual design and snappy interaction skillset match.",
    },
    tasks: [
      {
        id: "task-7",
        title: "Polish live demo project link before submitting",
        due_date: "2026-08-25",
        completed: false,
      },
      {
        id: "task-8",
        title: "Submit application on Linear careers portal",
        due_date: "2026-08-26",
        completed: false,
      },
    ],
    interview_rounds: [],
    created_at: "2026-08-24T12:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "app-6",
    company: "Shopify",
    role: "Staff Backend Engineer",
    status: "Rejected",
    priority: "Low",
    location: "Remote (Americas)",
    salary: "$170,000 - $200,000",
    date_applied: "2026-07-15",
    job_url: "https://shopify.com/careers",
    resume_version: "Backend_Focused_Resume.pdf",
    notes: "Role required 8+ years pure Ruby on Rails at massive monolith scale. Position closed internally.",
    job_description: "Scale high-volume checkout gateways and Ruby services.",
    match_insights: {
      score: 72,
      strengths: ["PostgreSQL", "API Security", "Caching", "Microservices"],
      gaps: ["Ruby on Rails 10+ yrs", "High-concurrency checkout scaling"],
      summary: "Good architectural skills but stack misalignment on Ruby internals.",
    },
    tasks: [],
    interview_rounds: [
      {
        id: "round-6",
        round_name: "Recruiter Screen",
        date: "2026-07-22",
        interviewer: "Shopify Talent",
        notes: "Recruiter indicated strong preference for deep Ruby monolith veterans.",
        status: "Completed",
      },
    ],
    created_at: "2026-07-15T08:00:00Z",
    updated_at: "2026-07-25T11:00:00Z",
  },
];
